{"errorMessage": "An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.", "errorType": "NoSuchKey", "requestId": "517a0c9d-174e-4826-8897-cecf2bd239b4", "stackTrace": ["  File \"/var/task/app.py\", line 49, in lambda_handler\n    response = s3_client.get_object(Bucket=bucket, Key=csv_key)\n", "  File \"/var/lang/lib/python3.12/site-packages/botocore/client.py\", line 598, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/var/lang/lib/python3.12/site-packages/botocore/context.py\", line 123, in wrapper\n    return func(*args, **kwargs)\n", "  File \"/var/lang/lib/python3.12/site-packages/botocore/client.py\", line 1061, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"]}